language: rust
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

branches:
  only:
    - master
    - dev

script:
  - cargo build --verbose
  - cargo test --verbose

cache: cargo