..\target\release\chrono-photo ^
--pattern ..\test_data\generated\image-*.jpg ^
--temp-dir ..\test_data\temp ^
--output ..\test_data\out.jpg ^
--output-blend ..\test_data\out-debug.png ^
--mode outlier ^
--threshold abs/0.1 ^
--background first ^
--outlier first ^
--quality 98 ^
--debug
